src/pages/Nav.vue
src/pages/UserInformation.vue
src/router/index.js

[feat] 개인정보 페이지 추가

---

src/pages/Student/StudentAside.vue
src/pages/Student/Studentdashboard.vue

[feat] 게시판 연동,시험 현황

---

src/pages/board/bbboard.vue
src/pages/board/bbnoticeboard.vue
src/pages/board/boardform.vue
src/pages/board/freeboard.vue
src/pages/board/managerboard.vue
src/pages/board/notice.vue
src/pages/board/question.vue

[Feat]게시판 글 수정

---

src/pages/Aside.vue

사이드바 링크 추가(대시보드, 게시판 연결)
대시보드 -> 학생 대시보드
게시판 -> 자유게시판

[feat] 사이드바 링크 추가(대시보드는 임의로 학생으로 설정)

---

src/pages/Aside.vue

[feat] 로그아웃 버튼 링크 추가

---

src/pages/LoginForm.vue

드롭다운 박스를 통해 어떤 계정으로 로그인 할지 변경
백엔드가 연결되지 않았기 때문에 오류나면 접속하는거라 좀 느림.
close #12

[feat] 로그인 접속 방식 변경

---

README.md
src/stores/useInstructorStore.js

[Feat] mock 업뎃 #14

---

src/pages/Student/StudentAside.vue

[feat] 학생 사이드바 로그아웃 링크 추가

---

src/pages/board/project.vue
src/router/index.js

[Feat] 과제 게시판 생성

---

src/pages/Student/StudentAside.vue
src/pages/Student/Studentdashboard.vue

[feat] student 링크 작업

---

src/pages/Instructor/InstructorDash.vue
src/router/index.js

[Feat] 강사링크연결 #23

---

src/pages/Instructor/InstStudInform.vue
src/router/index.js

강사의 학생정보 확인 페이지 링크 추가
index.js 중복 링크 삭제
close #23

[feat] 강사의 학생정보 확인 페이지 링크 추가

---

src/pages/Nav.vue

[feat] 헤더 로그아웃 링크 추가

---

src/pages/board/bbboard.vue
src/pages/board/bbnoticeboard.vue
src/pages/board/data.vue
src/pages/board/freeboard.vue
src/pages/board/notice.vue
src/pages/board/project.vue
src/router/index.js

[Feat]게시판 수정 및 생성

---

src/pages/board/bbboard.vue
src/pages/board/bbnoticeboard.vue
src/pages/board/boardform.vue
src/pages/board/components/BoardNav.vue
src/router/index.js

[feat] 게시판 카테고리 component화

---

src/pages/board/data.vue
src/router/index.js

[Fix]질의응답 경로 수정

---

src/pages/board/bbboard.vue
src/pages/board/bbnoticeboard.vue
src/pages/board/boardform.vue
src/pages/board/components/BoardNav.vue
src/pages/board/data.vue
src/pages/board/freeboard.vue

[fix] 컴포넌트 스크립트 오류 수정

---

src/pages/board/notice.vue
src/pages/board/project.vue
src/pages/board/question.vue

[fix] 나머지 게시판 컴포넌트화

---

src/pages/board/components/BoardNav.vue

[fix] 게시판 카테고리 링크 수정

---

src/pages/Student/Studentdashboard.vue

[fix] 과제현황에 과제 게시판 링크

---

src/pages/Student/Studentdashboard.vue

[fix] 출석 이미지 링크 에러 수정

---

src/pages/board/boardform.vue

[fix] 글 쓰기 페이지에서 탭 삭제

---

README.md
src/pages/Student/Studentdashboard.vue

[doc] readme 수정 #42

---

src/pages/board/boardform.vue

임시로 글 게시 클릭 시 이전 위치로 돌아가도록 함(강제로 뒤로가기)
시연용 임시조치이기 때문에 수정 필수

[feat] 글 작성시 전 위치로 돌아가기

---

src/pages/Instructor/components/TableData.vue
src/pages/Instructor/components/TableHw.vue

[Feat] 수정 이동 추가 #23

---

src/pages/board/components/TableRow.vue
src/pages/board/data.vue
src/pages/board/freeboard.vue
src/pages/board/notice.vue
src/pages/board/project.vue
src/pages/board/question.vue

각 게시판 항목 컴포넌트화(각 카테고리별 항목이 달라 일부 항목 미출력, 수정 예정)

[feat] 게시판 항목 컴포넌트화(미완)

---

src/pages/board/components/TableRow.vue
src/pages/board/data.vue
src/pages/board/freeboard.vue
src/pages/board/notice.vue
src/pages/board/project.vue
src/pages/board/question.vue

항목을 고정하지 않고 각 게시판 페이지에서 항목을 설정할 수 있도록 변경

[fix] 각 테이블의 항목별 컬럼에 맞게 설정

---

README.md
src/pages/Student/Studentdashboard.vue
src/pages/Student/components/Homework.vue

[feat] 학생 컴포넌트

---

src/pages/board/components/PageNav.vue
src/pages/board/data.vue
src/pages/board/freeboard.vue
src/pages/board/notice.vue
src/pages/board/project.vue
src/pages/board/question.vue

[feat] 게시판 목록 이동 컴포넌트화

---

src/main.js
src/pages/LoginForm.vue
src/pages/SignupForm.vue
src/stores/useMemberStore.js
vite.config.js

[Feat] 백엔드와 연결 로그인 기능 구현

---

src/pages/LoginForm.vue
src/pages/SignupForm.vue

[Feat] 회원가입 기능 백엔드와 연결 완료

---

src/pages/LoginForm.vue
src/pages/UserInformation.vue

[feat] 유저 정보 페이지 기능 추가

---

src/pages/board/boardform.vue
src/router/index.js
src/stores/useBoardStore.js

[Feat] 게시판 글쓰기 기능

---

src/pages/Aside.vue
src/pages/Nav.vue
src/pages/UserInformation.vue

로그아웃 버튼 기능 추가

---

src/pages/SignupForm.vue

임시로 회원 가입 시 역할 설정할 수 있도록 변경(추후 이메일로 인증해서 역할을 정할 수 있도록 변경 필요)

[feat][temp] 임시로 회원 가입 시 역할 설정할 수 있도록 변경(추후 이메일로 인증해서 역할을 정할 수 있도록 변경 필요)

---

package-lock.json
package.json
src/main.js
src/pages/Nav.vue
src/stores/useMemberStore.js

토큰 정보(이메일, 이름, idx)가 유지되도록 변경하여 네비게이션 바에 사용자 이름이 출력되도록 변경

[feat] 네비게이션 바에 사용자 이름이 출력되도록 변경

---

src/router/index.js

권한이 없는 경우 로그인 페이지로 이동

---

src/pages/Student/StudentAside.vue

[feat] 학생 사이드 바 로그인 기능 추가

---

index.html
src/pages/manager/ExamList.vue

매니저만 시험 추가 가능하도록 변경

---

src/pages/board/boardform.vue

게시글 추가 기능 구현
시험, 과제 제외 카테고리 추가 필요

[feat] 게시글 추가 기능 구현

---

src/pages/board/boardform.vue

사용자의 역할에 맞는 카테고리만 표시되며, 작성 완료 시 해당 카테고리의 리스트로 옮겨지도록 수정 완료

[feat] 게시글 작성 시 카테고리 선택 기능 추가

---

src/pages/Instructor/components/BoardDetail.vue
src/pages/Instructor/components/TableData.vue
src/pages/Instructor/components/TableHw.vue
src/pages/Instructor/components/UserCard2.vue
src/stores/useInstructorStore.js

[Feat] 강사 숙제, 자료 상세보기 팝업 추가 #96

---

src/pages/Instructor/InstStudInform.vue
src/pages/Instructor/InstructorDash.vue
src/pages/Instructor/components/TableBoard.vue
src/pages/Instructor/components/TableBoardStudInform.vue
src/pages/Instructor/components/UserCard2.vue
src/router/index.js
src/stores/useInstructorStore.js

[Feat] 강사 - 학생 상세보기 페이지 백엔드 연동 #98

---

src/pages/board/components/PageNav.vue
src/pages/board/components/TableRow.vue
src/pages/board/notice.vue
src/stores/useBoardStore.js

[feat] 공지 페이지 목록 출력

---

src/pages/board/components/TableRow.vue

[fix] 누락된 부분 수정

---

src/pages/board/data.vue
src/pages/board/freeboard.vue
src/pages/board/notice.vue
src/pages/board/project.vue
src/pages/board/question.vue

[feat] 각 카테고리별 게시글 목록 출력하도록 변경

---

src/pages/board/components/BoardNav.vue
src/pages/board/components/TableRow.vue

시험 카테고리 링크 수정, 카테고리 목록에서 글쓴이 출력 되도록 수정

[fix] 시험 카테고리 링크 수정, 글쓴이 출력 되도록 수정

---

src/pages/board/deleteboard.vue
src/pages/board/managerboard.vue
src/stores/useBoardStore.js

[Feat] 게시판 삭제 기능 

---

src/pages/board/freeboard.vue
src/stores/useBoardStore.js

[Feat] 게시판사용자 토큰큰

---

src/pages/board/bbboard.vue
src/pages/board/components/TableRow.vue
src/router/index.js
src/stores/useBoardStore.js

게시글 자세히보기 안되는 오류 해결

---

src/pages/Aside.vue
src/pages/UserInformation.vue

로그아웃 안되는 오류 해결
